version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/16
        gateway: 172.22.0.1

services:
  kdc:
    networks:
      custom:
        ipv4_address: 172.22.0.2
    image: kerberosperljava:latest
    hostname: kdc.kerberos.com
    extra_hosts:
      - "hadoop.docker.com:172.22.0.3"
    environment:
      REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com
    volumes:
      - "./config_files/krb5.conf:/etc/krb5.conf"
      - "/dev/urandom:/dev/random"
      - "/tmp/shared:/shared"
      #- "/etc/localtime:/etc/localtime:ro"

  hadoop-secure:
    networks:
      custom:
        ipv4_address: 172.22.0.3
    image: kerbhadoop
    depends_on: 
      - kdc
    hostname: hadoop
    domainname: docker.com
    tty: true
    extra_hosts:
      - "kdc.kerberos.com kdc:172.22.0.2"
    ports:
      - "8888:8888"
      - "8020:8020"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "8088:8088"
      - "10020:10020"
      - "19888:19888"
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com
      FQDN: hadoop.docker.com
    volumes:
      - "./config_files/krb5.conf:/etc/krb5.conf"
      - "/tmp/shared:/shared"
      #- "/etc/localtime:/etc/localtime:ro"